-- Databricks notebook source
-- MAGIC %md
-- MAGIC ##Lab 1. Ingest Medical Center locations

-- COMMAND ----------

-- MAGIC %run "../Lab 0 - Setup/SetCatalogName"

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ####Preview Medical Center Data

-- COMMAND ----------

select * from medicaid_providers.dbo.medicaid_providers

-- COMMAND ----------

CREATE OR REPLACE TABLE bronze.medical_providers
AS SELECT * FROM medicaid_providers.dbo.medicaid_providers

-- COMMAND ----------

-- MAGIC %md
-- MAGIC select all the columns from medicaid_providers.dbo.medicaid_providers replace spaces in the column names with underscore and create a new table called bronze.medical_providers

-- COMMAND ----------

CREATE OR REPLACE TABLE bronze.medical_providers AS
SELECT 
  `MEDICAID PROVIDER ID` AS MEDICAID_PROVIDER_ID, 
  NPI, 
  `PROVIDER OR FACILITY NAME` AS PROVIDER_OR_FACILITY_NAME, 
  `MEDICAID TYPE` AS MEDICAID_TYPE, 
  `PROFESSION OR SERVICE` AS PROFESSION_OR_SERVICE, 
  `PROVIDER SPECIALTY` AS PROVIDER_SPECIALTY, 
  `SERVICE ADDRESS` AS SERVICE_ADDRESS, 
  CITY, 
  STATE, 
  `ZIP CODE` AS ZIP_CODE, 
  COUNTY, 
  TELEPHONE, 
  LATITUDE, 
  LONGITUDE, 
  `ENROLLMENT BEGIN DATE` AS ENROLLMENT_BEGIN_DATE, 
  `NEXT ANTICIPATED REVALIDATION DATE` AS NEXT_ANTICIPATED_REVALIDATION_DATE, 
  `FILE DATE` AS FILE_DATE, 
  `MEDICALLY FRAGILE CHILDREN AND ADULTS DIRECTORY IND` AS MEDICALLY_FRAGILE_CHILDREN_AND_ADULTS_DIRECTORY_IND, 
  `PROVIDER EMAIL` AS PROVIDER_EMAIL
FROM medicaid_providers.dbo.medicaid_providers

-- COMMAND ----------

-- MAGIC %md
-- MAGIC
-- MAGIC ```sql 
-- MAGIC CREATE OR REPLACE TABLE bronze.medical_providers AS
-- MAGIC SELECT
-- MAGIC   `MEDICAID PROVIDER ID` AS MEDICAID_PROVIDER_ID,
-- MAGIC   NPI,
-- MAGIC   `PROVIDER OR FACILITY NAME` AS PROVIDER_OR_FACILITY_NAME,
-- MAGIC   `MEDICAID TYPE` AS MEDICAID_TYPE,
-- MAGIC   `PROFESSION OR SERVICE` AS PROFESSION_OR_SERVICE,
-- MAGIC   `PROVIDER SPECIALTY` AS PROVIDER_SPECIALTY,
-- MAGIC   `SERVICE ADDRESS` AS SERVICE_ADDRESS,
-- MAGIC   CITY,
-- MAGIC   STATE,
-- MAGIC   `ZIP CODE` AS ZIP_CODE,
-- MAGIC   COUNTY,
-- MAGIC   TELEPHONE,
-- MAGIC   LATITUDE,
-- MAGIC   LONGITUDE,
-- MAGIC   `ENROLLMENT BEGIN DATE` AS ENROLLMENT_BEGIN_DATE, 
-- MAGIC   `NEXT ANTICIPATED REVALIDATION DATE` AS NEXT_ANTICIPATED_REVALIDATION_DATE, 
-- MAGIC   `FILE DATE` AS FILE_DATE, 
-- MAGIC   `MEDICALLY FRAGILE CHILDREN AND ADULTS DIRECTORY IND` AS MEDICALLY_FRAGILE_CHILDREN_AND_ADULTS_DIRECTORY_IND, 
-- MAGIC   `PROVIDER EMAIL` AS PROVIDER_EMAIL
-- MAGIC FROM medicaid_providers.dbo.medicaid_providers
-- MAGIC ```
